<?php
//
// +----------------------------------------------------------------------+
// |zen-cart Open Source E-commerce                                       |
// +----------------------------------------------------------------------+
// | Copyright (c) 2003 The zen-cart developers                           |
// |                                                                      |
// | http://www.zen-cart.com/index.php                                    |
// |                                                                      |
// | Portions Copyright (c) 2003 osCommerce                               |
// +----------------------------------------------------------------------+
// | This source file is subject to version 2.0 of the GPL license,       |
// | that is bundled with this package in the file LICENSE, and is        |
// | available through the world-wide-web at the following url:           |
// | http://www.zen-cart.com/license/2_0.txt.                             |
// | If you did not receive a copy of the zen-cart license and are unable |
// | to obtain it through the world-wide-web, please send a note to       |
// | license@zen-cart.com so we can mail you a copy immediately.          |
// +----------------------------------------------------------------------+
// $Id: tpl_product_info_display.php,v 1.2 2005/08/03 13:26:00 spiderr Exp $
//
// Variables available on this page
//
// $products_name
// $products_model
// $products_price
// $specials_price
// $products_image @@TODO Consider using a array generated by a class for multiple images
// $products_url
// $products_date_available
// $products_date_added
// $products_description
// $products_manufacturer
// $products_weight
// $products_quantity
// $options_name - Array
// $options_menu - Array
?>
<?php echo zen_draw_form('cart_quantity', zen_href_link(FILENAME_PRODUCT_INFO, zen_get_all_get_params(array('action')) . 'action=add_product')); ?>
<?php if (PRODUCT_INFO_PREVIOUS_NEXT=='1') { ?>
	<div><?php require($template->get_template_dir('/tpl_products_next_previous.php',DIR_WS_TEMPLATE, $current_page_base,'templates'). '/tpl_products_next_previous.php'); ?>
</div>
<?php } ?>
<h1><?php echo $products_name; ?></h1>
<div class="productbox">
	<div class="productimage">
		<?php if (zen_not_null($products_image)) { ?>
			<script language="javascript" type="text/javascript"><!--
				document.write('<?php echo '<a href="javascript:popupWindow(\\\'' . zen_href_link(FILENAME_POPUP_IMAGE, 'products_id=' . $_GET['products_id']) . '\\\')">' . zen_image(DIR_WS_IMAGES . $products_image, addslashes($products_name), SMALL_IMAGE_WIDTH, SMALL_IMAGE_HEIGHT, 'hspace="5" vspace="5"') . '</a><br /><a href="javascript:popupWindow(\\\'' . zen_href_link(FILENAME_POPUP_IMAGE, 'products_id=' . $_GET['products_id']) . '\\\')">' . TEXT_CLICK_TO_ENLARGE . '</a>'; ?>');
			//--></script>
			<noscript>
				<?php echo '<a href="' . zen_href_link(DIR_WS_IMAGES . $products_image) . '" target="_blank">' . zen_image(DIR_WS_IMAGES . $products_image, $products_name, SMALL_IMAGE_WIDTH, SMALL_IMAGE_HEIGHT, 'hspace="5" vspace="5"') . '</a><br /><a href="' . zen_href_link(DIR_WS_IMAGES . $products_image) . '" target="_blank">' . TEXT_CLICK_TO_ENLARGE . '</a>'; ?>
			</noscript>
		<?php } ?>

		<?php if ($specials_price) { ?>
		  <p class="specialprice"><span class="normalprice"><?php echo $products_price; ?></span> <?php echo $specials_price; ?></p>
		<?php } else { echo "<p class=\"price\">" . $products_price . "</p>";  } ?>

		<p><?php echo (!empty($manufacturers_name) ? TEXT_PRODUCT_MANUFACTURER . $manufacturers_name : ''); ?></p>
	</div> <!-- close productimage -->

	<div class="productfeatures">
		<div class="formrow"><?php echo "<label>" . TEXT_PRODUCT_MODEL . "</label>" . $products_model; ?></div>

		<?php echo ($products_weight !=0 ? '<div class="formrow"><label>' . TEXT_PRODUCT_WEIGHT . '</label>' . $products_weight . TEXT_PRODUCT_WEIGHT_UNIT . '</div>' : ''); ?>

		<?php echo '<div class="formrow"><label>' . TEXT_PRODUCT_QUANTITY . '</label>' . $products_quantity . '</div>'; ?>

		<?php if ($pr_attr->fields['total'] > 0) { ?>
			<fieldset><legend><?php echo TEXT_PRODUCT_OPTIONS; ?></legend>
			<?php for($i=0;$i<sizeof($options_name);$i++) { echo '<div class="formrow"><label>' . $options_name[$i] . ':</label>' . $options_menu[$i] . '</div>'; } ?>
			<br style="clear:both"/>
			</fieldset>
		<?php } ?>

		<?php echo ( (SHOW_IN_CART_QTY_PRODUCT_INFO and ($_SESSION['cart']->in_cart($_GET['products_id']) or $_SESSION['cart']->in_cart($_GET['products_id']))) ? '<div class="formrow"><label>' . PRODUCTS_ORDER_QTY_TEXT_IN_CART . '</label>' . $_SESSION['cart']->get_quantity($_GET['products_id']) . '</div>' : ''); ?>
		<?php echo '<div class="formrow"><label>' . PRODUCTS_ORDER_QTY_TEXT . '</label>'; ?><input type="text" name="cart_quantity" value="1" maxlength="6" size="4" /><?php echo zen_draw_hidden_field('products_id', (int)$_GET['products_id']) . zen_image_submit('button_in_cart.gif', IMAGE_BUTTON_IN_CART) . '</div>'; ?>

	</div> <!-- close productfeatures -->
	<br style="clear:both" />
</div> <!-- close productbox -->
</form>
<?php require($template->get_template_dir('/tpl_products_features.php',DIR_WS_TEMPLATE, $current_page_base,'templates'). '/tpl_products_features.php'); ?>
<div class="productdescription"><?php echo stripslashes($products_description); ?></div>

<?php if (PRODUCT_INFO_PREVIOUS_NEXT=='2') { ?>
	<div><?php require(DIR_WS_INCLUDES . 'products_next_previous.php'); ?></div>
<?php } ?>

<?php if ($reviews->fields['count'] > 0) { ?>
	<div id="reviews">
		<?php echo TEXT_CURRENT_REVIEWS . ' ' . $reviews->fields['count']; ?>
    	<?php echo '<a href="' . zen_href_link(FILENAME_PRODUCT_REVIEWS, zen_get_all_get_params()) . '">' . zen_image_button('button_reviews.gif', IMAGE_BUTTON_REVIEWS) . '</a>'; ?>
    </div>
<?php } ?>

<div class="center">
	<?php if ($products_date_available > date('Y-m-d H:i:s')) { ?>
		<p class="smalltext"><?php echo sprintf(TEXT_DATE_AVAILABLE, zen_date_long($products_date_available)); ?></p>
	<?php } else { echo '<p class="smalltext">' . sprintf(TEXT_DATE_ADDED, zen_date_long($products_date_added)) . '</p>'; } ?>
	
	<?php if (zen_not_null($products_url)) { ?>
		<p><?php echo sprintf(TEXT_MORE_INFORMATION, zen_href_link(FILENAME_REDIRECT, 'action=url&goto=' . urlencode($products_url), 'NONSSL', true, false)); ?></p>
	<?php } ?>
</div>